fo=open("file.txt",'w')
fo.write("Hello!!Its python file /n Python is Developed by GUIDO VAN RUSSOM")
fo.close()
fo=open("file.txt",'r+')
str=fo.read()
data=str.split()
w=len(str)
l=len(data)
print("Total Characters in the file is :",w)
print("Total Words in the file is :",l)
fo.close()